development:
  adapter: postgresql
  encoding: unicode
  database: metropolis_quickstart_development
  pool: 5
  port: 5431
  host: docker.for.mac.host.internal
  # host: localhost
  username: postgres