project                = "hello-metropolis"
credentials_file       = "gcp-service-account.json"
cluster_name           = "metropolis-quickstart-sandbox"
metropolis_public_key  = "1850b8d876b2"
metropolis_private_key = "1206d2595582a736b5ea0ea8acb078b8"
zone                   = "us-west1-c"
region                 = "us-west1"